// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

var Curry   = require("bs-platform/lib/js/curry.js");
var React   = require("react");
var ReactRe = require("reason-react/lib/js/src/reactRe.js");

var componentDidMount = ReactRe.Component[0];

var componentWillUpdate = ReactRe.Component[1];

var componentDidUpdate = ReactRe.Component[2];

var componentWillReceiveProps = ReactRe.Component[3];

var componentWillUnmount = ReactRe.Component[4];

var getInstanceVars = ReactRe.Component[5];

var jsPropsToReasonProps = ReactRe.Component[6];

var getInitialState = ReactRe.Component[7];

var name = "Yo";

var items_000 = React.createElement("div", undefined, "Yo");

var items_001 = /* :: */[
  React.createElement("div", undefined, "Yo"),
  /* :: */[
    React.createElement("div", undefined, "Yo"),
    /* :: */[
      React.createElement("div", undefined, "Yo"),
      /* [] */0
    ]
  ]
];

var items = /* :: */[
  items_000,
  items_001
];

function render() {
  return React.createElement("div", undefined, ReactRe.listToElement(items));
}

var Yo_008 = /* Stateful */ReactRe.Component[8];

var Yo_009 = /* JsProps */ReactRe.Component[9];

var Yo_010 = /* InstanceVars */ReactRe.Component[10];

var Yo = /* module */[
  /* componentDidMount */componentDidMount,
  /* componentWillUpdate */componentWillUpdate,
  /* componentDidUpdate */componentDidUpdate,
  /* componentWillReceiveProps */componentWillReceiveProps,
  /* componentWillUnmount */componentWillUnmount,
  /* getInstanceVars */getInstanceVars,
  /* jsPropsToReasonProps */jsPropsToReasonProps,
  /* getInitialState */getInitialState,
  Yo_008,
  Yo_009,
  Yo_010,
  /* name */name,
  /* items */items,
  /* render */render
];

var include = ReactRe.CreateComponent([
      name,
      getInstanceVars,
      getInitialState,
      componentDidMount,
      componentWillReceiveProps,
      componentWillUpdate,
      componentDidUpdate,
      componentWillUnmount,
      jsPropsToReasonProps,
      render
    ]);

var wrapProps = include[1];

function createElement(count) {
  return Curry._1(wrapProps, /* record */[/* count */count]);
}

var comp = include[0];

exports.Yo            = Yo;
exports.comp          = comp;
exports.wrapProps     = wrapProps;
exports.createElement = createElement;
/* items Not a pure module */
